### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by zhusas** [ZhuoRoger/redismon#3]
root@Redis-Server1:/opt/redismon/bin# python redis_monitor.py 
Traceback (most recent call last):
  File "redis_monitor.py", line 122, in <module>
    main()
  File "redis_monitor.py", line 119, in main
    redis_falcon_monitor.send_data()
  File "redis_monitor.py", line 74, in send_data
    redis_server_info_dict = redis_server_info.collect_info_data() 
  File "/opt/redismon/bin/redis_server.py", line 76, in collect_info_data
    redisInfo,redisInfoCmdStat,redis_maxclients,redis_maxmemory = self.redis_info()
  File "/opt/redismon/bin/redis_server.py", line 45, in redis_info
    redisInfoCmdStat = redis_cli.info("commandstats")   #All cmdstat_xx nfo
TypeError: info() takes exactly 1 argument (2 given)

如上图，请大神指教

**Comment by ZhuoRoger** [comment]
看下是不是redis版本过低了
